In [1]:
#Fazendo a importação da biblioteca necessária e dando um alias para facilitar o desenvolvimento.
import pandas as pd

In [2]:
#Por questão de boas práticas, a variável responsável por receber o dataset se chamará df.
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")

In [3]:
#Ao chamar a variável que recebeu o dataset, os dados serão exibidos de forma formatada.
df

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0             1  Montagem          72.62          41.77           111      0
1             2  Usinagem          81.65          34.08           128      0
2             3  Usinagem          68.87          39.44           159      0
3             4  Usinagem          66.84          34.52            98      0
4             5  Usinagem          66.23          31.57            94      0
5             6  Usinagem          64.79          37.09            83      0
6             7  Usinagem          85.02          36.34           106      1
7             8  Inspeção          60.31          33.77           124      0
8             9  Montagem          75.84          29.65            92      0
9            10  Inspeção          68.38          28.93           145      1
10           11  Usinagem          76.31          35.48           149      0
11           12  Inspeção          74.79          33.37           134      0
12           13  Usinagem          76.31          36.51           154      0
13           14  Montagem          63.28          33.71           129      0
14           15  Montagem          64.98          33.24            83      0
15           16  Montagem          81.48          30.50           102      0
16           17  Montagem          79.62          39.68            85      1
17           18  Inspeção          69.80          27.20            91      0
18           19  Inspeção          77.16          47.45            99      0
19           20  Usinagem          73.30          39.77           119      1
20           21  Inspeção          79.77          38.04            91      0
21           22  Usinagem          71.76          35.16            80      0
22           23  Inspeção          74.16          31.93           149      0
23           24  Usinagem          74.69          32.34           123      1
24           25  Usinagem          74.03          32.71           145      1
25           26  Usinagem          75.96          38.70            93      0
26           27  Usinagem          60.80          37.18           159      0
27           28  Montagem          69.37          35.90           122      1
28           29  Montagem          70.28          35.04           103      0
29           30  Inspeção          73.53          32.84            82      0
30           31  Montagem          63.59          42.29           159      1
31           32  Inspeção          68.91          32.66           155      0
32           33  Inspeção          77.62          35.70           108      1
33           34  Inspeção          73.32          32.18           129      1
34           35  Usinagem          78.24          31.93           158      0
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [4]:
#Por padrão a função head exibe as primeiras 5 linhas do dataset. Ao inserir um número dentro do parênteses, o número inserido será o número de linhas.
df.head()

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [5]:
#O tail vai exibir as últimas linhas do dataset, por padrão ele exibe as 5 últimas.
df.tail()

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [6]:
#O shape é uma ferramenta que vai exibir as dimensões do dataset, sendo elas: (quantidade de linhas no dataset, quantidade de colunas no dataset).
df.shape

(40, 6)

In [7]:
#info() é uma função que exibe as informações sobre o dataset.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.3 KB

In [8]:
#columns é uma ferramenta que exibe as colunas presentes no dataset.
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [9]:
#o .isna() vai procurar por valores que estão nulos e o .sum vai fazer a soma de todos esses valores nulos.
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [10]:
#Exibe os valores não nulos.
df.notnull()

    id_registro  setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0          True   True           True           True          True   True
1          True   True           True           True          True   True
2          True   True           True           True          True   True
3          True   True           True           True          True   True
4          True   True           True           True          True   True
5          True   True           True           True          True   True
6          True   True           True           True          True   True
7          True   True           True           True          True   True
8          True   True           True           True          True   True
9          True   True           True           True          True   True
10         True   True           True           True          True   True
11         True   True           True           True          True   True
12         True   True           True           True          True   True
13         True   True           True           True          True   True
14         True   True           True           True          True   True
15         True   True           True           True          True   True
16         True   True           True           True          True   True
17         True   True           True           True          True   True
18         True   True           True           True          True   True
19         True   True           True           True          True   True
20         True   True           True           True          True   True
21         True   True           True           True          True   True
22         True   True           True           True          True   True
23         True   True           True           True          True   True
24         True   True           True           True          True   True
25         True   True           True           True          True   True
26         True   True           True           True          True   True
27         True   True           True           True          True   True
28         True   True           True           True          True   True
29         True   True           True           True          True   True
30         True   True           True           True          True   True
31         True   True           True           True          True   True
32         True   True           True           True          True   True
33         True   True           True           True          True   True
34         True   True           True           True          True   True
35         True   True           True           True          True   True
36         True   True           True           True          True   True
37         True   True           True           True          True   True
38         True   True           True           True          True   True
39         True   True           True           True          True   True

In [11]:
#Exibe só os valoes de uma coluna específica.
df["temperatura_c"]

0     72.62
1     81.65
2     68.87
3     66.84
4     66.23
5     64.79
6     85.02
7     60.31
8     75.84
9     68.38
10    76.31
11    74.79
12    76.31
13    63.28
14    64.98
15    81.48
16    79.62
17    69.80
18    77.16
19    73.30
20    79.77
21    71.76
22    74.16
23    74.69
24    74.03
25    75.96
26    60.80
27    69.37
28    70.28
29    73.53
30    63.59
31    68.91
32    77.62
33    73.32
34    78.24
35    68.47
36    75.62
37    78.50
38    76.19
39    68.64
Name: temperatura_c, dtype: float64

In [12]:
#Para exibir mais de uma coluna, é preciso fazer dentro de mais um colchete.
df[["temperatura_c", "setor"]]

    temperatura_c     setor
0           72.62  Montagem
1           81.65  Usinagem
2           68.87  Usinagem
3           66.84  Usinagem
4           66.23  Usinagem
5           64.79  Usinagem
6           85.02  Usinagem
7           60.31  Inspeção
8           75.84  Montagem
9           68.38  Inspeção
10          76.31  Usinagem
11          74.79  Inspeção
12          76.31  Usinagem
13          63.28  Montagem
14          64.98  Montagem
15          81.48  Montagem
16          79.62  Montagem
17          69.80  Inspeção
18          77.16  Inspeção
19          73.30  Usinagem
20          79.77  Inspeção
21          71.76  Usinagem
22          74.16  Inspeção
23          74.69  Usinagem
24          74.03  Usinagem
25          75.96  Usinagem
26          60.80  Usinagem
27          69.37  Montagem
28          70.28  Montagem
29          73.53  Inspeção
30          63.59  Montagem
31          68.91  Inspeção
32          77.62  Inspeção
33          73.32  Inspeção
34          78.24  Usinagem
35          68.47  Usinagem
36          75.62  Inspeção
37          78.50  Usinagem
38          76.19  Montagem
39          68.64  Montagem

In [13]:
#Comando para visualizar as colunas em formato de lista.
df.columns.to_list()

['id_registro',
 'setor',
 'temperatura_c',
 'tempo_ciclo_s',
 'producao_dia',
 'falha']

In [14]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

## Exercício
- Importar a biblioteca pandas
- Realizar a leitura dos dados
- Exibir os 5 primeiros dados
- Exibir os 5 últimos dados
- Exibir a quantidade de linhas e colunas
- Exibir as informações gerais da base de dados
- Realizar a contagem de valores não nulos
- Exibir os nomes das colunas
- Exibir a descrição (min, max, mean, std, quartis)

In [15]:
#Importar a biblioteca pandas
import pandas as pd

In [16]:
#Realizar a leitura dos dados
df = pd.read_csv(r"data\dataset_aula01_techshop_vendas.csv")
# df

In [17]:
#Exibir os 5 primeiros dados
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [18]:
#Exibir os 5 últimos dados
df.tail()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [19]:
#Exibir a quantidade de linhas e colunas
df.shape

(800, 7)

In [20]:
#Exibir as informações gerais da base de dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 70.9 KB

In [21]:
#Realizar a contagem de valores não nulos
df.isna().sum()

data_pedido        0
categoria          0
preco_unitario     0
quantidade         0
regiao             0
canal_marketing    0
avaliacao          0
dtype: int64

In [22]:
#Exibir os nomes das colunas
df.columns

Index(['data_pedido', 'categoria', 'preco_unitario', 'quantidade', 'regiao',
       'canal_marketing', 'avaliacao'],
      dtype='str')

In [23]:
#Exibir a descrição (min, max, mean, std, quartis)
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [24]:
#Criação de novas colunas com base em outras, por exemplo, a coluna faturamento.
df["faturamento"] = df["preco_unitario"] * df["quantidade"]
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao,faturamento
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3,36.20
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4,613.05
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6,604.76
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1,6798.32
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9,6361.88

In [25]:
#Fazer o tratamento da base de dados
df = pd.read_csv(r"data\dataset_aula01_techshop_vendas.csv", parse_dates=["data_pedido"])
#Exibir resultado para testar se deu certo.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    datetime64[us]
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 63.1 KB

In [26]:
#Criar uma cópia da database que já foi tratada ou manipulada.
df_tratado = df.copy()

In [27]:
#Adição da coluna "faturamento" na database já tratada.
df_tratado["faturamento"] = df_tratado["preco_unitario"] * df_tratado["quantidade"]
df_tratado.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao,faturamento
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3,36.20
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4,613.05
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6,604.76
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1,6798.32
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9,6361.88

In [28]:
#Fazer a soma de todos os valores presentes em uma coluna, nesse caso, a soma da coluna faturamento.
df_tratado["faturamento"].sum()

np.float64(2847624.13)

In [29]:
#É possível também fazer um print dessa operação, assim eliminando algumas informações desnecesárias.
print(df_tratado["faturamento"].sum())

2847624.13

In [30]:
#É possível também atribuir essa operação em uma variável
faturamento_total = df_tratado["faturamento"].sum()
print(f"O faturamento é de R${faturamento_total}.")

O faturamento é de R$2847624.13.

In [31]:
#Formatação da variável, executando replaces para as substituições adequadas.
faturamento_correto = f"{faturamento_total:,.2f}".replace(",","x").replace(".",",").replace("x",".")
print(f"O faturamento total foi de R${faturamento_correto}.")

O faturamento total foi de R$2.847.624,13.

In [32]:
#Realizar agrupamentos para realizar os faturamentos por categoria
df_tratado.groupby("categoria")["faturamento"].sum()

categoria
Acessórios     103851.41
Notebooks      922453.90
Smartphones    970236.71
TVs            463526.50
Áudio          387555.61
Name: faturamento, dtype: float64

In [33]:
#Realizar o agrupamento e também organizar em ordem crescente.
df_tratado.groupby("categoria")["faturamento"].sum().sort_values()

categoria
Acessórios     103851.41
Áudio          387555.61
TVs            463526.50
Notebooks      922453.90
Smartphones    970236.71
Name: faturamento, dtype: float64

In [34]:
#Agrupamento com base por região.
df_tratado.groupby("regiao")["faturamento"].sum().sort_values()

regiao
Norte            188452.12
Centro-Oeste     313101.36
Sul              509659.07
Nordeste         548131.32
Sudeste         1288280.26
Name: faturamento, dtype: float64

In [35]:
#Agrupamento com base por região em ordem descrescente.
df_tratado.groupby("regiao")["faturamento"].sum().sort_values(ascending=False)

regiao
Sudeste         1288280.26
Nordeste         548131.32
Sul              509659.07
Centro-Oeste     313101.36
Norte            188452.12
Name: faturamento, dtype: float64

In [36]:
df_tratado.groupby(["regiao","categoria"])["faturamento"].sum()

regiao        categoria
Centro-Oeste  Acessórios       8656.88
              Notebooks       99033.37
              Smartphones     77194.16
              TVs             89348.05
              Áudio           38868.90
Nordeste      Acessórios      18718.42
              Notebooks      217721.24
              Smartphones    151958.99
              TVs             95584.37
              Áudio           64148.30
Norte         Acessórios      10172.29
              Notebooks       45019.79
              Smartphones     76691.66
              TVs             24573.88
              Áudio           31994.50
Sudeste       Acessórios      48978.07
              Notebooks      438034.81
              Smartphones    444644.12
              TVs            178412.29
              Áudio          178210.97
Sul           Acessórios      17325.75
              Notebooks      122644.69
              Smartphones    219747.78
              TVs             75607.91
              Áudio           74332.94
Name: faturamento, dtype: float64

In [37]:
#Criar função para formatar os valores
def converter(valor):
    return f"R${valor:,.2f}".replace(",","x").replace(".",",").replace("x",".")

In [38]:
#Teste da função de conversão.
agrupamento_faturamento_regiao = df_tratado.groupby("regiao")["faturamento"].sum()
agrupamento_faturamento_regiao.map(converter)

regiao
Centro-Oeste      R$313.101,36
Nordeste          R$548.131,32
Norte             R$188.452,12
Sudeste         R$1.288.280,26
Sul               R$509.659,07
Name: faturamento, dtype: str

In [39]:
#Move o dataset modificado para o dataframe padrão.
df = df_tratado.copy()

In [40]:
#Gera o arquivo tratado dentro da pasta.
df.to_csv("dataset_tratado.csv")