Conceito de n-gramas

In [328]:
frase = "O amor é cego o amor é forte e o amor vence tudo"

Função `.split()` é usada para pegar todas as palavas de uma string e agrupar a frase numa lista.

In [329]:
palavras = frase.split()
palavras

['O',
 'amor',
 'é',
 'cego',
 'o',
 'amor',
 'é',
 'forte',
 'e',
 'o',
 'amor',
 'vence',
 'tudo']

Importação da biblioteca `pandas` para montar um dataframe usando a lista de palavras geradas.

In [330]:
import pandas as pd
tabela = pd.DataFrame({"palavra":palavras})
tabela

   palavra
0        O
1     amor
2        é
3     cego
4        o
5     amor
6        é
7    forte
8        e
9        o
10    amor
11   vence
12    tudo

Uma representação gráfica de previsão de palavras.

In [331]:
tabela["proxima_palavra"] = tabela["palavra"].shift(-1)
tabela

   palavra proxima_palavra
0        O            amor
1     amor               é
2        é            cego
3     cego               o
4        o            amor
5     amor               é
6        é           forte
7    forte               e
8        e               o
9        o            amor
10    amor           vence
11   vence            tudo
12    tudo             NaN

Tratativa para remover a última linha que estava com um `NaN`.

In [332]:
tabela = tabela.dropna()
tabela

   palavra proxima_palavra
0        O            amor
1     amor               é
2        é            cego
3     cego               o
4        o            amor
5     amor               é
6        é           forte
7    forte               e
8        e               o
9        o            amor
10    amor           vence
11   vence            tudo

Filtragem para exibir os casos que tem a palavra `amor` e as palavras que vem depois dele.

In [333]:
filtro = tabela["palavra"] == "amor"
tabela[filtro]

   palavra proxima_palavra
1     amor               é
5     amor               é
10    amor           vence

Contagem das palavras que vem depois de `amor`, fazendo a exibição de porcentagem das respectivas palavras.

In [334]:
tabela[filtro]["proxima_palavra"].value_counts(normalize = True)

proxima_palavra
é        0.666667
vence    0.333333
Name: proportion, dtype: float64

Função para chamar qual palavra que mais tem chance de aparecer depois do `amor`.

In [335]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'é'

Testes para ver qual será a próxima palavra

In [336]:
filtro = tabela["palavra"] == "amor"
tabela[filtro]

   palavra proxima_palavra
1     amor               é
5     amor               é
10    amor           vence

In [337]:
tabela[filtro]["proxima_palavra"].value_counts(normalize = True)

proxima_palavra
é        0.666667
vence    0.333333
Name: proportion, dtype: float64

In [338]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'é'

O resultado foi um loop de `O amor é cego o amor é cego o amor é cego...`